[versions]
lombok-plugin = "8.14"
spring-boot = "4.0.0"
spring-dependency-plugin = "1.1.7"
openapi-plugin = "1.9.0"
spring-cloud = "5.0.0"
jline = "3.30.6"
pf4j = "3.13.0"
pf4j-spring = "0.10.0"

[libraries]
# --- Spring Boot ---
spring-boot-starter-web = { group = "org.springframework.boot", name = "spring-boot-starter-web", version.ref = "spring-boot" }
spring-boot-starter-webflux = { group = "org.springframework.boot", name = "spring-boot-starter-webflux", version.ref = "spring-boot" }

# --- Spring Cloud ---
spring-cloud-starter-eureka-server = { group = "org.springframework.cloud", name = "spring-cloud-starter-netflix-eureka-server", version.ref = "spring-cloud" }
spring-cloud-starter-gateway-webflux = { group = "org.springframework.cloud", name = "spring-cloud-gateway-server-webflux", version.ref = "spring-cloud" }
spring-cloud-starter-loadbalancer = { module = "org.springframework.cloud:spring-cloud-starter-loadbalancer", version.ref = "spring-cloud" }
resilience4j = { group = "org.springframework.cloud", name = "spring-cloud-starter-circuitbreaker-reactor-resilience4j", version.ref = "spring-cloud" }

# --- Shell ---
jline = { group = "org.jline", name = "jline-terminal-jna", version.ref = "jline" }

# --- Plugins ---
pf4j = { group = "org.pf4j", name = "pf4j", version.ref = "pf4j" }
pf4j-spring = { group = "org.pf4j", name = "pf4j-spring", version.ref = "pf4j-spring" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency = { id = "io.spring.dependency-management", version.ref = "spring-dependency-plugin" }
lombok = { id = "io.freefair.lombok", version.ref = "lombok-plugin" }
openapi = { id = "org.springdoc.openapi-gradle-plugin", version.ref = "openapi-plugin" }