services:
  user-profile:
    build:
      context: ../
      dockerfile: services/user-profile/Dockerfile
    ports:
      - "${USER_PROFILE_PORT:-1027}:1027"
    env_file:
      - ".env"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s
    networks:
      - oclick-net

networks:
  oclick-net:
    name: oclick-net
    driver: bridge