services:
  pg_keycloak:
    image: postgres:18
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-oclick}
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      KC_DB_USERNAME: ${KC_DB_USERNAME:-keycloak}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD:-keycloak}
    volumes:
      - pgdata:/var/lib/postgresql
      - ./postgres/init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${KC_DB_USERNAME:-keycloak} -d keycloak" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - oclick-net
      - pg_net

  keycloak:
    image: quay.io/keycloak/keycloak:26.4
    ports:
      - "${KEYCLOAK_HTTP_PORT:-7080}:7080"
      - "${KEYCLOAK_HTTPS_PORT:-7443}:7443"
      - "${KEYCLOAK_MANAGEMENT_PORT:-9000}:9000"
    environment:
      KC_DB: postgres
      KC_DB_URL: ${KC_DB_JDBC_URL}
      KC_DB_USERNAME: ${KC_DB_USERNAME:-keycloak}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD:-keycloak}
      KC_HOSTNAME: https://auth.xqxq.site
      KC_HOSTNAME_STRICT: false
      KC_PROXY_HEADERS: xforwarded
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_ADMIN_USERNAME:-keycloak}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_ADMIN_PASSWORD:-keycloak}
      KC_LOG_LEVEL: info
    healthcheck:
      test: [ "CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/9000; echo -e 'GET /health/ready HTTP/1.1\r\nHost: localhost:9000\r\nConnection: close\r\n\r\n' >&3;cat <&3 | grep -q '\"status\": \"UP\"' && exit 0 || exit 1" ]
      interval: 15s
      timeout: 2s
      retries: 4
    command: [
      "start-dev",
      "--http-port", "7080",
      "--https-port", "7443",
      "--import-realm",
      "--verbose",
      "--health-enabled=true",
      "--metrics-enabled=true"
    ]
    env_file:
      - ".env"
    volumes:
      - ./keycloak/import:/opt/keycloak/data/import
      - ./keycloak/providers:/opt/keycloak/providers
    depends_on:
      pg_keycloak:
        condition: service_healthy
    networks:
      - oclick-net

volumes:
  pgdata:
networks:
  oclick-net:
    name: oclick-net
    driver: bridge