services:
  eureka:
    build:
      context: ../
      dockerfile: platform/eureka-server/Dockerfile
    ports:
      - "${EUREKA_PORT:-8761}:8761"
    env_file:
      - ".env"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s
    networks:
      - oclick-net

networks:
  oclick-net:
    name: oclick-net
    driver: bridge