spring:
  application:
    name: eureka-server

server:
  port: 2001

eureka:
  server:
    wait-time-in-ms-when-sync-empty: 300000
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 0
  client:
    register-with-eureka: false
    fetch-registry: false
management:
  server:
    port: 2002