server:
  port: ${VACANCY_SERVICE_PORT:1026}
management:
  server:
    port: 8081
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
    registry-fetch-interval-seconds: 30
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 90
    lease-renewal-interval-in-seconds: 30
spring:
  application:
    name: vacancy-service