server:
  port: ${USER_PROFILE_PORT:1025}
management:
  server:
    port: 8081
spring:
  application:
    name: user-profile
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
    registry-fetch-interval-seconds: 30
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 5